### PR TITLE
#164829313 Sets up file and folder structure for react and redux workflow

### PR DESCRIPTION
**Pull request by Raywire**
**What does this PR do?**
Sets up Redux for Authors Haven frontend.
**Description of the tasks to be completed**

1. Create the folder structure for react/redux workflow
2. Create the relevant files for setting up redux

**Relevant PT stories**
[164829313](https://www.pivotaltracker.com/story/show/164829313)

### CODE REVIEW

**Review by MainaKamau92 — DISMISSED** [review]

**Review by Kyppy — COMMENTED** [review]
Did you create an article view already or was that just for testing? If it was just for testing maybe it should not have been pushed? Please help me understand the purpose of 'ArticleList'.js.

**Comment by Raywire** [comment]
> Did you create an article view already or was that just for testing? If it was just for testing maybe it should not have been pushed? Please help me understand the purpose of 'ArticleList'.

The files I created show the react-redux workflow by removing them it will become harder to understand how to set this up on next week's features. That is foresight to create a consistent way for us to interact with redux.

**Comment by Kyppy** [comment]
> > Did you create an article view already or was that just for testing? If it was just for testing maybe it should not have been pushed? Please help me understand the purpose of 'ArticleList'.
> 
> The files I created show the react-redux workflow by removing them it will become harder to understand how to set this up on next week's features. That is foresight to create a consistent way for us to interact with redux.

Then perhaps it is best you include this workflow in your PR or the README. What you have included will be helpful but it does not contribute to what the client wants, it is for us as developers. So I don't think it makes sense to include it in the codebase. Perhaps we discuss with Waithira or the team to see if this is a good practice?

**Comment by Raywire** [comment]
> > > Did you create an article view already or was that just for testing? If it was just for testing maybe it should not have been pushed? Please help me understand the purpose of 'ArticleList'.
> > 
> > 
> > The files I created show the react-redux workflow by removing them it will become harder to understand how to set this up on next week's features. That is foresight to create a consistent way for us to interact with redux.
> 
> Then perhaps it is best you include this workflow in your PR or the README. What you have included will be helpful but it does not contribute to what the client wants, it is for us as developers. So I don't think it makes sense to include it in the codebase. Perhaps we discuss with Waithira or the team to see if this is a good practice?

We need those files to setup react-redux beyond simply doing 'npm install'.

> > > Did you create an article view already or was that just for testing? If it was just for testing maybe it should not have been pushed? Please help me understand the purpose of 'ArticleList'.
> > 
> > 
> > The files I created show the react-redux workflow by removing them it will become harder to understand how to set this up on next week's features. That is foresight to create a consistent way for us to interact with redux.
> 
> Then perhaps it is best you include this workflow in your PR or the README. What you have included will be helpful but it does not contribute to what the client wants, it is for us as developers. So I don't think it makes sense to include it in the codebase. Perhaps we discuss with Waithira or the team to see if this is a good practice?

We can discuss it with the team.

**Review by kihuha — APPROVED** [review]

**Review by MainaKamau92 — APPROVED** [review]

**Pull request merged**
